language: java
addons:
  sonarcloud:
    organization: "antobrines"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dsonar.projectKey=antobrines_ipi-java-350-ex